apiVersion: v1
kind: Service
metadata:
  name: chemgraph-streamlit
  labels:
    app: chemgraph
    component: streamlit
spec:
  type: LoadBalancer
  selector:
    app: chemgraph
    component: streamlit
  ports:
  - name: http
    protocol: TCP
    port: 8501
    targetPort: 8501
